// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textsemibolditalic provides the "STIXTwoText SemiBoldItalic" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textsemibolditalic // import "github.com/go-fonts/stix/stix2textsemibolditalic"

import _ "embed"

// TTF is the data for the "STIXTwoText SemiBoldItalic" TrueType font.
//
//go:embed STIXTwoText-SemiBoldItalic.otf
var TTF []byte
