// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textbold provides the "STIX2Text Bold" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textbold // import "github.com/go-fonts/stix/stix2textbold"

import _ "embed"

// TTF is the data for the "STIX2Text Bold" TrueType font.
//
//go:embed STIX2Text-Bold.otf
var TTF []byte
