// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textbolditalic provides the "STIXTwoText BoldItalic" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textbolditalic // import "github.com/go-fonts/stix/stix2textbolditalic"

import _ "embed"

// TTF is the data for the "STIXTwoText BoldItalic" TrueType font.
//
//go:embed STIXTwoText-BoldItalic.otf
var TTF []byte
