// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textitalic provides the "STIXTwoText Italic" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textitalic // import "github.com/go-fonts/stix/stix2textitalic"

import _ "embed"

// TTF is the data for the "STIXTwoText Italic" TrueType font.
//
//go:embed STIXTwoText-Italic.otf
var TTF []byte
