// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textmedium provides the "STIXTwoText Medium" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textmedium // import "github.com/go-fonts/stix/stix2textmedium"

import _ "embed"

// TTF is the data for the "STIXTwoText Medium" TrueType font.
//
//go:embed STIXTwoText-Medium.otf
var TTF []byte
