// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textsemibold provides the "STIXTwoText SemiBold" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textsemibold // import "github.com/go-fonts/stix/stix2textsemibold"

import _ "embed"

// TTF is the data for the "STIXTwoText SemiBold" TrueType font.
//
//go:embed STIXTwoText-SemiBold.otf
var TTF []byte
