// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textregular provides the "STIX2Text Regular" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textregular // import "github.com/go-fonts/stix/stix2textregular"

import _ "embed"

// TTF is the data for the "STIX2Text Regular" TrueType font.
//
//go:embed STIX2Text-Regular.otf
var TTF []byte
