// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2textmediumitalic provides the "STIXTwoText MediumItalic" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2textmediumitalic // import "github.com/go-fonts/stix/stix2textmediumitalic"

import _ "embed"

// TTF is the data for the "STIXTwoText MediumItalic" TrueType font.
//
//go:embed STIXTwoText-MediumItalic.otf
var TTF []byte
