// generated by go run gen-fonts.go; DO NOT EDIT

// Package stix2mathregular provides the "STIXTwoMath Regular" TrueType font
// from the STIX2 font family. It is a proportional-width, serif font.
package stix2mathregular // import "github.com/go-fonts/stix/stix2mathregular"

import _ "embed"

// TTF is the data for the "STIXTwoMath Regular" TrueType font.
//
//go:embed STIXTwoMath-Regular.otf
var TTF []byte
